### ISSUE TITLE
Navbar animation is broken

### ISSUE THREAD

**Issue by Skilled5041** [Skilled5041/ccc-trainer-website#23]
The animation flickers when hovering the brackets at a specific point. It works normally if you hover at the center. My cursor isn't being recorded by screen recorder for some reason.

https://github.com/Skilled5041/ccc-trainer-website/assets/93156908/0289074f-dcb4-4a27-b105-f0bb3c9c260d

**Comment by danielp1218** [comment]
Fixed it in my pull request :)
